Heading control not final tuning, just for code review
Iron-Panthers/2024-offseason pull request #14
Opened 2024-12-10 19:17 UTC by NoraZitnick

Heading control works but needs to be tuned, angle wrap around does work. Uses trapezoidal profile and pid.

2025-01-05 09:51 UTC, JayK445 requested changes
Excited to hear that this is working, but would like workshop the changes and lessen their footprint if possible.

2025-01-05 09:51 UTC, JayK445 commented on src/main/java/frc/robot/subsystems/swerve/Drive.java
> +  /*radians*/
Can we decouple the "heading control" functionality from the pre-existing teleop control function? Grouping them may cause confusion later down the line (esp. for integrating in autos, etc.).

(ie. create a single setHeadingLock(), push integration with teleop to RobotContainer)

2025-01-05 09:51 UTC, JayK445 commented on src/main/java/frc/robot/subsystems/swerve/Drive.java
> +      }
What is the purpose of this statement?

2025-01-05 09:51 UTC, JayK445 commented on src/main/java/frc/robot/subsystems/swerve/controllers/HeadingController.java
> +  public Rotation2d update(Rotation2d yaw, double currentRotationalVelocity) {
What is the purpose of currentRotationalVelocity? It doesn't appear to be used yet.

2025-01-05 09:51 UTC, JayK445 commented on src/main/java/frc/robot/subsystems/swerve/controllers/TeleopController.java
> +    double omega = controllerOmega;
Why remove the deadband?

2025-01-05 09:51 UTC, JayK445 commented on src/main/java/frc/robot/subsystems/swerve/controllers/HeadingController.java
> +    Logger.recordOutput("Swerve/TargetHeading", normalizeRadians(targetRotation2d.getRadians()));
Consider applying normalizeRadians() in setTarget(). We want data logged to be the same as what is used.

2025-01-05 09:51 UTC, JayK445 commented on src/main/java/frc/robot/subsystems/swerve/controllers/HeadingController.java
> +  public double normalizeRadians(double radians) {
Is this supposed to be private?

2025-01-05 09:51 UTC, JayK445 commented on src/main/java/frc/robot/RobotContainer.java
>                  () -> {
Can we break up the operations here? 
(ie. calculate the "heading" separately, etc)

2025-01-05 10:17 UTC, JayK445 commented on src/main/java/frc/robot/subsystems/swerve/Drive.java
> +  /*radians*/
Consider using a supplier to pass in the target(s).

2025-01-06 23:11 UTC, NoraZitnick commented on src/main/java/frc/robot/subsystems/swerve/Drive.java
> +      }
This method is so you can choose not use heading control, and so it sets the headingController to null, telling the periodic to not use heading controller

2025-01-07 05:45 UTC, NoraZitnick commented on src/main/java/frc/robot/subsystems/swerve/controllers/HeadingController.java
> +  public Rotation2d update(Rotation2d yaw, double currentRotationalVelocity) {
Was going to be used for trapeziodal profiling but not needed now

2025-01-14 01:25 UTC, closed without merging